-- Script for mysql

CREATE TABLE USERS(USER_ID INTEGER PRIMARY KEY, ENABLED INTEGER, USERNAME VARCHAR(100), PASSWORD VARCHAR(100));

CREATE TABLE USER_ROLES(USER_ROLE_ID INTEGER PRIMARY KEY, USER_ID INTEGER, AUTHORITY VARCHAR(100));

insert into users(user_id, ENABLED, USERNAME, PASSWORD) values(1,1,'a','a');
insert into users(user_id, ENABLED, USERNAME, PASSWORD) values(2,1,'b','b');

insert into user_roles(USER_ROLE_ID, USER_ID,AUTHORITY) VALUES(1,1,'ROLE_USER');
insert into user_roles(USER_ROLE_ID, USER_ID,AUTHORITY) VALUES(2,2,'ROLE_ADMIN');